### GET request to example server
GET http://localhost:8080/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOiJVU0VSIiwic3ViIjoiZ3VpbGhlcm1lQGVtYWlsLmNvbSIsImV4cCI6MTc4MjYyODE0NX0.flt5nQxc1DoOhJ9ApPvbKPtLWRdsa2DdgHMrSg2Xt8w
#Authorization: Bearer <token de USER ou ADMIN>


###

GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOiJBRE1JTiIsInN1YiI6Imd1aWxoZXJtZUBtYWlsLmNvbSIsImV4cCI6MTc4MjYyODE0NX0.flt5nQxc1DoOhJ9ApPvbKPtLWRdsa2DdgHMrSg2Xt8w
#Authorization: Bearer <token de ADMIN>

###

DELETE http://localhost:8080/users/1
Authorization: Bearer <token de ADMIN>

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Guilherme",
  "email": "guilherme@email.com",
  "password": "guilherme123",
  "role": "USER"
}

###

POST http://localhost:8080/auth/register
Content-Type: application/json
Authorization: Bearer <token de ADMIN>

{
  "name": "Admin",
  "email": "admin@email.com",
  "password": "admin123",
  "role": "ADMIN"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "hugo@email.com",
    "password": "hugo123"
}