### GET request to example server
GET http://localhost:8080/test
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInN1YiI6Imd1aWxoZXJtZUBlbWFpbC5jb20iLCJleHAiOjE3ODIyNzU1NjF9.jZP-SQmGo-LUXTJtGjxIU4YmTZjxQI1vaXhjuzVS5Lk


###

GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInN1YiI6Imd1aWxoZXJtZUBlbWFpbC5jb20iLCJleHAiOjE3ODIyNzU1NjF9.jZP-SQmGo-LUXTJtGjxIU4YmTZjxQI1vaXhjuzVS5Lk

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Guilherme",
  "email": "guilherme@email.com",
  "password": "guilherme123"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "hugo@email.com",
    "password": "hugo123"
}