spring:
  config:
    import: optional:classpath:application-local.yaml
  flyway:
    enabled: true
  application:
    name: demo
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}

github:
  oauth:
    client-id: ${GITHUB_OAUTH_CLIENT_ID:}
    client-secret: ${GITHUB_OAUTH_CLIENT_SECRET:}
    scope: ${GITHUB_OAUTH_SCOPE:read:user,user:email}
    redirect-uri: ${GITHUB_OAUTH_REDIRECT_URI:http://localhost:8080/login/github/auth}

google:
  oauth:
    client-id: ${GOOGLE_OAUTH_CLIENT_ID:}
    client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET:}
    redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URI:http://localhost:8080/login/google/auth}
